# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_nanas.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 578)
        MainWindow.setStyleSheet("background-color:rgb(224, 255, 166)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(160, 330, 221, 171))
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_9.setGeometry(QtCore.QRect(10, 40, 101, 23))
        self.pushButton_9.setStyleSheet("background-color: rgb(208, 255, 157)\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_10.setGeometry(QtCore.QRect(120, 40, 91, 23))
        self.pushButton_10.setStyleSheet("background-color: rgb(208, 255, 157)")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_11.setGeometry(QtCore.QRect(10, 80, 101, 23))
        self.pushButton_11.setStyleSheet("background-color: rgb(208, 255, 157)")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_12.setGeometry(QtCore.QRect(120, 80, 91, 23))
        self.pushButton_12.setStyleSheet("background-color: rgb(208, 255, 157)")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_17.setGeometry(QtCore.QRect(80, 120, 75, 23))
        self.pushButton_17.setStyleSheet("background-color: rgb(208, 255, 157)")
        self.pushButton_17.setObjectName("pushButton_17")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 10, 431, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(0, 0, 0)")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 30, 311, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 100, 251, 221))
        self.groupBox_3.setStyleSheet("background-color:rgb(208, 255, 157)")
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(400, 360, 331, 101))
        self.groupBox_6.setStyleSheet("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_11 = QtWidgets.QLabel(self.groupBox_6)
        self.label_11.setGeometry(QtCore.QRect(10, 40, 161, 31))
        self.label_11.setObjectName("label_11")
        self.textEdit_20 = QtWidgets.QTextEdit(self.groupBox_6)
        self.textEdit_20.setGeometry(QtCore.QRect(180, 30, 131, 51))
        self.textEdit_20.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.textEdit_20.setObjectName("textEdit_20")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(270, 100, 251, 221))
        self.groupBox_4.setStyleSheet("background-color:rgb(208, 255, 157)")
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(530, 100, 251, 221))
        self.groupBox_5.setStyleSheet("background-color:rgb(208, 255, 157)")
        self.groupBox_5.setObjectName("groupBox_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Kontrol"))
        self.pushButton_9.setText(_translate("MainWindow", "Start"))
        self.pushButton_10.setText(_translate("MainWindow", "Capture"))
        self.pushButton_11.setText(_translate("MainWindow", "Proses"))
        self.pushButton_12.setText(_translate("MainWindow", "Save"))
        self.pushButton_17.setText(_translate("MainWindow", "Exit"))
        self.label_2.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">DETEKSI KEMATENGAN NANAS MENGGUNAKAN METODE</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-style:italic; color:#000000;\">Convolutional Neural Network</span><span style=\" font-size:12pt; color:#000000;\"> (CNN)</span></p></body></html>"))
        self.groupBox_3.setTitle(_translate("MainWindow", "kamera"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Hasi Output"))
        self.label_11.setText(_translate("MainWindow", "Persentase Kematangan Nanas :"))
        self.textEdit_20.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">%</span></p></body></html>"))
        self.groupBox_4.setTitle(_translate("MainWindow", "capture"))
        self.groupBox_5.setTitle(_translate("MainWindow", "output"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
